### ISSUE TITLE
Got banned!

### ISSUE THREAD

**Issue by THEG77** [hellbound1337/nitro-sniper#2]
The description is completely true.
My account got banned randomly within 3 hours after running this.

Just wanted to let this out. Use this but keep in mind that your account may and probably will get disabled.

**Comment by GiorgioBrux** [comment]
Are you sure you got banned for this and not something else?
The sniper doesn't even log into the main account, only in slaves. Did you put your main token in `guildTokens`?

**Comment by hellbound1337** [comment]
Make sure you use a throwaway account(s) that is/are in tons of guilds for guildTokens instead of using your main account for both. While you still have the chance to be terminated it will decrease the risks, i have recently added duplication checking and it now detects OBVIOUS invalid codes and doesn't redeem them which should help a lot.
